/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tauqe' at '18/08/19 01:57' with Gradle 2.14.1
 *
 * @author tauqe, @date 18/08/19 01:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
